name: Create Issue and Add to Project
on:
  issues:
    types: opened

jobs:
  create-issue:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          issue_title="New Issue Title"
          issue_body="Description of the issue."
          project_column_id=12345  # Replace with your project column ID
          repository_owner=${{ github.repository_owner }}
          repository_name=${{ github.event.repository.name }}

          # Create the issue and capture the response
          response=$(curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d "{\"title\":\"$issue_title\",\"body\":\"$issue_body\",\"labels\":[],\"assignees\":[]}" \
            "https://api.github.com/repos/$repository_owner/$repository_name/issues")

          # Extract the issue number from the response
          issue_number=$(echo $response | jq -r '.number')

          # Add the issue to the project
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d "{}" \
            "https://api.github.com/projects/columns/cards/$project_column_id/notes"

          echo "Issue $issue_number has been created and added to the project."

