# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Move opened card
on:
  issues:
    types: [opened]

jobs:
  move-assigned-card:
    runs-on: macos-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: i2p_project
          column: In Progress
          repo-token: ${{ secrets.SECRET_PAT_I2P }}